---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-nudger-persister
  name: http-nudger-persister
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-nudger-persister
  template:
    metadata:
      labels:
        app: http-nudger-persister
    spec:
      containers:
      - name: http-nudger-google
        image: http-nudger:0.1.0-1
        args:
        - persister
        envFrom:
        - configMapRef:
            name: aiven-kafka
        - secretRef:
            name: aiven-postgres
        volumeMounts:
        - name: aiven-kafka-tls
          mountPath: /home/http-nudger
      volumes:
      - name: aiven-kafka-tls
        secret:
          secretName: aiven-kafka-tls
